---
- name: Retrieve Fabric Interconnect Information
  cisco.intersight.intersight_rest_api:
    api_private_key: "{{ api_auth.api_private_key }}"
    api_key_id: "{{ api_auth.api_key_id }}"
    api_uri: "{{ api_auth.api_uri | default('https://intersight.com/api/v1') }}"
    validate_certs: "{{ api_auth.validate_certs | default(true) }}"
    resource_path: /network/ElementSummaries
    query_params:
      $filter: "SwitchType eq 'FabricInterconnect'"
      $top: 10
    return_list: true  # Ensures API response is a list
  register: ucs_fi_pre_provision_check_fi_data
  delegate_to: localhost

- name: Extract FI Information for Specific Host
  ansible.builtin.set_fact:
    ucs_fi_pre_provision_check_fi_selected: "{{ ucs_fi_pre_provision_check_fi_data.api_response | selectattr('Name', 'equalto', inventory_hostname) | list | first }}"

- name: Count Total, Used, and Available Ports
  ansible.builtin.set_fact:
    ucs_fi_pre_provision_check_total_ports: "{{ fi_selected.NumEtherPorts | int + fi_selected.NumFcPorts | int }}"
    ucs_fi_pre_provision_check_used_ports: "{{ fi_selected.NumEtherPortsConfigured | int + fi_selected.NumFcPortsConfigured | int }}"

- name: Count Available Ports
  ansible.builtin.set_fact:
    ucs_fi_pre_provision_check_available_ports: "{{ ucs_fi_pre_provision_check_total_ports | int - ucs_fi_pre_provision_check_used_ports | int }}"

- name: FI Switch Ports Information
  ansible.builtin.debug:
    msg:
      ModTime: "{{ ucs_fi_pre_provision_check_fi_selected.ModTime }}"
      Model: "{{ ucs_fi_pre_provision_check_fi_selected.Model }}"
      Moid: "{{ ucs_fi_pre_provision_check_fi_selected.Moid }}"
      Name: "{{ ucs_fi_pre_provision_check_fi_selected.Name }}"
      NumEtherPorts: "{{ ucs_fi_pre_provision_check_fi_selected.NumEtherPorts }}"
      NumEtherPortsConfigured: "{{ ucs_fi_pre_provision_check_fi_selected.NumEtherPortsConfigured }}"
      NumEtherPortsLinkUp: "{{ ucs_fi_pre_provision_check_fi_selected.NumEtherPortsLinkUp }}"
      NumExpansionModules: "{{ ucs_fi_pre_provision_check_fi_selected.NumExpansionModules }}"
      NumFcPorts: "{{ ucs_fi_pre_provision_check_fi_selected.NumFcPorts }}"
      NumFcPortsConfigured: "{{ ucs_fi_pre_provision_check_fi_selected.NumFcPortsConfigured }}"
      NumFcPortsLinkUp: "{{ ucs_fi_pre_provision_check_fi_selected.NumFcPortsLinkUp }}"
      SwitchId: "{{ ucs_fi_pre_provision_check_fi_selected.SwitchId }}"

- name: Port Summary
  ansible.builtin.debug:
    msg:
      Total Ports: "{{ ucs_fi_pre_provision_check_total_ports }}"
      Used Ports: "{{ ucs_fi_pre_provision_check_used_ports }}"
      Available Ports: "{{ ucs_fi_pre_provision_check_available_ports }}"

- name: Fail if No Available Ports
  ansible.builtin.fail:
    msg: "All ports are occupied. Provisioning cannot proceed."
  when: ucs_fi_pre_provision_check_available_ports | int == 0

- name: Provisioning Check
  ansible.builtin.debug:
    msg: "Provisioning  for '{{ fi_selected.Name }}' can proceed. {{ ucs_fi_pre_provision_check_available_ports }} ports are available."
  when: ucs_fi_pre_provision_check_available_ports | int > 0
