---
- name: Initialize provisioning result list
  set_fact:
    ucs_fi_port_query_details: []

- name: Loop through each Fabric Interconnect
  ansible.builtin.include_tasks: "fi_port_query.yml"
  loop: "{{ ucs_fi_port_query_fi_list }}"
  loop_control:
    loop_var: current_fi


- name: Display consolidated FI port query results
  ansible.builtin.debug:
    msg: "{{ ucs_fi_port_query_details }}"