---
- name: "Verify required variables are defined and not empty"
  ansible.builtin.fail:
    msg: "{{ item }} is not defined or empty"
  when: "vars[item] is not defined or (vars[item] | length == 0)"
  loop:
    - "upgrade_ucs_fi_firmware_fi_list"

- name: Fail if upgrade_ucs_fi_firmware_distributable_type is set but not upgrade_ucs_fi_firmware_distributable_version
  ansible.builtin.fail:
    msg: "upgrade_ucs_fi_firmware_distributable_type is set. Please set upgrade_ucs_fi_firmware_distributable_version"
  when: upgrade_ucs_fi_firmware_distributable_type == "specific_version" and upgrade_ucs_fi_firmware_distributable_version is not defined

- name: Upgrade FI firmware
  ansible.builtin.include_tasks: upgrade_fi_firmware.yml
  loop: "{{ upgrade_ucs_fi_firmware_fi_list }}"
  loop_control:
    loop_var: fi_name
